#!/usr/bin/env bash

for item in $(find ${PWD}/lib -type f | grep "\.ts$" | sort); do
    tsc --newLine LF --noImplicitAny --removeComments --preserveConstEnums --target es5 --module commonjs $item;
done
