#!/usr/bin/env bash

for item in $(find ./lib -type f | grep "\.ts$" | sort); do
    tsc --newLine LF --sourceMap --noImplicitAny --removeComments --preserveConstEnums --target es5 --module commonjs ${item};
done

./bin/generateKindType --output ./lib/jsPreProcessorForTypeScript/compiler/KindType.ts
tsc --newLine LF --sourceMap --noImplicitAny --removeComments --preserveConstEnums --target es5 --module commonjs\
    ./lib/jsPreProcessorForTypeScript/compiler/KindType.ts;
