import IDaemonBase = require("../../daemon/IDaemon");
import IException  = require("../exception/IException");
import IResponse   = require("../IResponse");
import IMemory     = require("../../memory/client/IClient");

interface IDaemon extends IDaemonBase {
    namespace:string;
    metadataNamespace:string;
    binaryNamespace:string;
    gzipNamespace:string;
    lockNamespace:string;
    sourceDirectory:string;
    includeDirectories:string[];
    useIndex:boolean;
    indexExtensions:string[];
    useGzip:boolean;
    gzipMinLength:number;
    gzipExtensions:string[];
    gzipCompressionLevel:number;
    memory:IMemory;
    metadataMemory:IMemory;
    binaryMemory:IMemory;
    gzipMemory:IMemory;
    lockMemory:IMemory;
    getNamespace():string;
    setNamespace(namespace:string):void;
    getMetadataNamespace():string;
    setMetadataNamespace(namespace:string):void;
    getBinaryNamespace():string;
    setBinaryNamespace(namespace:string):void;
    getGzipNamespace():string;
    setGzipNamespace(namespace:string):void;
    getLockNamespace():string;
    setLockNamespace(namespace:string):void;
    getIncludeDirectories():string[];
    setIncludeDirectories(directories:string[]):void;
    getSourcesDirectory():string;
    setSourcesDirectory(directory:string):void;
    isUseIndex():boolean;
    getIsUseIndex():boolean;
    setIsUseIndex(value:boolean):void;
    getIndexExtensions():string[];
    setIndexExtensions(extensions:string[]):void;
    isUseGzip():boolean;
    getIsUseGzip():boolean;
    setIsUseGzip(value:boolean):void;
    getGzipMinLength():number;
    setGzipMinLength(length:number):void;
    getGzipExtensions():string[];
    setGzipExtensions(extensions:string[]):void;
    getGzipCompressionLevel():number;
    setGzipCompressionLevel(level:number):void;
    getMemory():IMemory;
    getMetadataMemory():IMemory;
    getBinaryMemory():IMemory;
    getGzipMemory():IMemory;
    getLockMemory():IMemory;
    getContent(filename:string, callback?:(errors:IException[], result:IResponse) => void):void;
}

export = IDaemon;
